name: Deploy to ECS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  S3_BUCKET: ${{ secrets.S3_BUCKET }}
  CLOUDFRONT_DISTRIBUTION: ${{ secrets.CLOUDFRONT_DISTRIBUTION }}

  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  build-and-upload-frontend:
    name: build and upload frontend
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Push build to S3 (destructive)
        env:
          CLOUDFRONT_DISTRIBUTION: ${{ env.CLOUDFRONT_DISTRIBUTION }}
        run: |
          yarn install
          yarn build
          aws s3 sync ./build s3://${{ env.S3_BUCKET }} --delete
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION --paths "/*"
